DROP TABLE IF EXISTS USER;

CREATE TABLE USER
(
    ID       BIGINT(20)  NOT NULL COMMENT '主键ID',
    NAME     VARCHAR(30) NULL DEFAULT NULL COMMENT '姓名',
    AGE      INT(11)     NULL DEFAULT NULL COMMENT '年龄',
    EMAIL    VARCHAR(50) NULL DEFAULT NULL COMMENT '邮箱',
    PASSWORD VARCHAR(30) NULL DEFAULT NULL COMMENT '密码',
    PRIMARY KEY (ID)
);

CREATE TABLE `PRODUCT`
(
    `ID`            BIGINT(20)   NOT NULL,
    `NAME`          VARCHAR(50)  NOT NULL,
    `PRODUCT_CODE`  VARCHAR(100) NOT NULL,
    `CATEGORY_CODE` VARCHAR(50)    DEFAULT NULL COMMENT '类别',
    `DESCRIPTION`   VARCHAR(5120)  DEFAULT NULL,
    `PRICE`         DECIMAL(10, 2) DEFAULT NULL COMMENT '价格',
    `STOCK`         INT(255)       DEFAULT NULL COMMENT '库存',
    PRIMARY KEY (`ID`)
);

CREATE TABLE `ORDER`
(
    ID           BIGINT(20)  NOT NULL COMMENT '主键ID',
    USER_ID      BIGINT(20)  NOT NULL COMMENT 'USER_ID',
    PRODUCT_ID   BIGINT(20)  NOT NULL COMMENT 'USER_ID',
    PRICE        DECIMAL(10, 2) DEFAULT NULL COMMENT '价格',
    COUNT        INT(255)       DEFAULT NULL COMMENT '购买数量',
    TOTAL_AMOUNT DECIMAL(10, 2) DEFAULT NULL COMMENT '总金额',
    STATUS       VARCHAR(50) NOT NULL COMMENT '订单状态， NEW, PAID, CANCEL, EXPIRED, DONE',
    PRIMARY KEY (`ID`)
);

